### ISSUE TITLE
Support for 1.1.4-2 kotlin

### ISSUE THREAD

**Issue by xMickeymikex** [nhaarman/mockito-kotlin#196] opened 2017-08-30 06:25 UTC
Hey, since kotlin have updated their std to 1.1.4-2 it would be nice to have it in mockito-kotlin as well, as it does create a conflict which prevents our project from compilation.

**Comment by nhaarman** [comment] 2017-08-30 11:41
Duplicate of #181, there is a solution there as well.

**Closed by nhaarman** 2017-08-30 11:41 UTC

**Comment by leodeleon22** [comment] 2017-08-30 15:15
That's my build.gradle I still have the problem 

```
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    
    testCompile 'org.jetbrains.spek:spek-api:1.1.2'
    testCompile 'org.jetbrains.spek:spek-junit-platform-engine:1.1.2'
    testCompile 'org.junit.platform:junit-platform-runner:1.0.0-RC1'
    testCompile 'org.mockito:mockito-core:2.5.0'
    testCompile 'com.nhaarman:mockito-kotlin-kt1.1:1.5.0', { exclude group: 'org.jetbrains.kotlin' }
```

**Comment by nhaarman** [comment] 2017-08-30 15:18
You can explicitly depend on the correct kotlin reflect version:

```
testCompile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
```
